version: '3.9'

services:

  postgres:
    container_name: posts.postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
    ports:
      - ${DATABASE_PORT}:5432
    restart: unless-stopped

